name: camcode
description: A camera barcode scanner for Flutter Web using your favorite Javascript library
version: 2.2.1
repository: https://github.com/PiotrFLEURY/camcode
homepage: https://camcode-59c70.web.app/

flutter:
  plugin:
    platforms:
      android:
        package: com.example.camcode
        pluginClass: CamcodePlugin
      ios:
        pluginClass: CamcodePlugin
      web:
        pluginClass: CamcodeWeb
        fileName: camcode_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.22.6"